-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgtDo7WI8/8Perjt64
ZF2sHPlvp17gN62gENybD6t/nxCgCgYIKoZIzj0DAQehRANCAATOfHOA9QJb+tXS
kJiVvuwQlmNJFUEXQPpCLr5H6/WUoUeARNNrnFIj9YS+hycDl0cATPjweheqK6fF
OVYkyv0K
-----END PRIVATE KEY-----